version: '3'

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./:/www:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9080:80
  php:
    build: ./docker/php
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/www:ro
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: soldout
      MYSQL_PASSWORD: soldout
      MYSQL_DATABASE: soldout
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 9000:80
    environment:
      PMA_USER: soldout
      PMA_PASSWORD: soldout
      PMA_HOST: db
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 9001:8080
volumes:
  db-data:
