# vim: set et ts=2 sw=2:

version: '3.2'

services:
  web:
    image: soldout-web:latest
    depends_on:
      - php
    volumes:
      - app-data:/soldout/data:ro
    environment:
      TZ: Europe/Rome
    ports:
      - "80:80"
  php:
    image: soldout-php:latest
    depends_on:
      - db
    volumes:
      - ./env-config.php:/soldout/www/env-config.php:ro
      - app-data:/soldout/data
    environment:
      TZ: Europe/Rome
  db:
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      TZ: Europe/Rome
      MYSQL_ROOT_PASSWORD: soldout
      MYSQL_USER: soldout
      MYSQL_PASSWORD: soldout
      MYSQL_DATABASE: soldout
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8001:8080"
    depends_on:
      - db

volumes:
  db-data:
  app-data:
