version: '3.2'

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./:/soldout/source:ro
      - app-data:/soldout/data:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
  php:
    build: ./docker/php
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/soldout/source:ro
      - app-data:/soldout/data
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: soldout
      MYSQL_PASSWORD: soldout
      MYSQL_DATABASE: soldout
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 9001:8080
volumes:
  db-data:
  app-data:
