# vim: set et ts=2 sw=2:

version: '3.2'

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./:/soldout/source:ro
      - app-data:/soldout/data:ro
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      TZ: Europe/Rome
    ports:
      - "80:80"
  php:
    build: ./docker/php
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/soldout/source:ro
      - app-data:/soldout/data
    environment:
      TZ: Europe/Rome
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      TZ: Europe/Rome
      MYSQL_ROOT_PASSWORD: soldout
      MYSQL_USER: soldout
      MYSQL_PASSWORD: soldout
      MYSQL_DATABASE: soldout
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8001:8080"
    depends_on:
      - db
  devtools:
    build:
      context: .
      dockerfile: ./docker/dev-tools.Dockerfile
    environment:
      TZ: Europe/Rome
    user: "1000:1000"
    volumes:
      - ./:/app

volumes:
  db-data:
  app-data:
